Repository Taucher2003/Appenders, pull requests merged in 2021-08, with the labels that each got.

#44 Removed automatic addition of label in Github IsssueAppenders.
  core/src/main/java/com/github/taucher2003/appenders/core/github/IssueAppender.java
Labels: topic: appender, type: improvement

#47 Add Issue Templates
  .github/ISSUE_TEMPLATE/appender_improvement.md
  .github/ISSUE_TEMPLATE/appender_request.md
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/logging_framework_request.md
Labels: type: meta

#42 Add Support for Gitlab Appenders
  README.md
  all/pom.xml
  core/pom.xml
  core/src/main/java/com/github/taucher2003/appenders/core/AbstractWebAppender.java
  core/src/main/java/com/github/taucher2003/appenders/core/gitlab/AbstractGitlabAppender.java
  core/src/main/java/com/github/taucher2003/appenders/core/gitlab/CommentingIssueAppender.java
  core/src/main/java/com/github/taucher2003/appenders/core/gitlab/IssueAppender.java
  log4j/pom.xml
  log4j/src/main/java/com/github/taucher2003/appenders/log4j/gitlab/AbstractLog4JGitlabAppender.java
  log4j/src/main/java/com/github/taucher2003/appenders/log4j/gitlab/Log4JCommentingIssueAppender.java
  log4j/src/main/java/com/github/taucher2003/appenders/log4j/gitlab/Log4JIssueAppender.java
  logback/pom.xml
  logback/src/main/java/com/github/taucher2003/appenders/logback/gitlab/AbstractLogbackGitlabAppender.java
  logback/src/main/java/com/github/taucher2003/appenders/logback/gitlab/LogbackCommentingIssueAppender.java
  logback/src/main/java/com/github/taucher2003/appenders/logback/gitlab/LogbackIssueAppender.java
  pom.xml
  utils/pom.xml
  utils/src/main/java/com/github/taucher2003/appenders/utils/Utilities.java
  utils/src/main/java/com/github/taucher2003/appenders/utils/WebRequestExecutor.java
  utils/src/main/java/com/github/taucher2003/appenders/utils/buckets/GitlabBucket.java
  utils/src/main/java/com/github/taucher2003/appenders/utils/executors/GitlabWebRequestExecutor.java
Labels: type: enhancement, topic: appender

#48 Improve CI Deployments
  .github/workflows/deploy.yml
  .gitlab-ci.yml
  README.md
  all/pom.xml
  core/pom.xml
  gitlab_deployment.xml
  log4j/pom.xml
  logback/pom.xml
  pom.xml
  utils/pom.xml
Labels: type: meta

#51 Update deployment names
  .github/workflows/deploy.yml
Labels: type: meta

#53 Add Descriptions to all Modules
  all/pom.xml
  core/pom.xml
  log4j/pom.xml
  logback/pom.xml
  pom.xml
  utils/pom.xml
Labels: type: meta

#54 Change dependabot configuration
  .github/dependabot.yml
Labels: topic: dependencies, type: meta

#56 Change Description of Branch versions
  README.md
Labels: type: documentation, type: meta

#59 Add Security scanning
  .gitlab-ci.yml
Labels: type: enhancement, topic: ci/cd
